import { makeHappyDrums, repeat, withDrums } from './helpers'

export const song = withDrums({
  key: 'happy',
  emoji: '😊',
  lyrics: [
    "If you're happy and you know it, clap your hands!",
    "If you're happy and you know it, clap your hands!",
    "If you're happy and you know it, then your face will surely show it,",
    "If you're happy and you know it, clap your hands!",
    '',
    "If you're happy and you know it, stomp your feet!",
    "If you're happy and you know it, stomp your feet!",
    "If you're happy and you know it, then your face will surely show it,",
    "If you're happy and you know it, stomp your feet!",
    '',
    "If you're happy and you know it, shout hurray!",
    "If you're happy and you know it, shout hurray!",
    "If you're happy and you know it, then your face will surely show it,",
    "If you're happy and you know it, shout hurray!",
  ],
  notes: repeat([
    { pitch: 'C4', dur: 1 }, { pitch: 'C4', dur: 0.5 },
    { pitch: 'F4', dur: 1 }, { pitch: 'F4', dur: 0.5 },
    { pitch: 'F4', dur: 1 }, { pitch: 'F4', dur: 0.5 },
    { pitch: 'F4', dur: 1 }, { pitch: 'F4', dur: 0.5 },
    { pitch: 'E4', dur: 1 }, { pitch: 'F4', dur: 0.5 },
    { pitch: 'G4', dur: 1.5 },
    { pitch: '', dur: 1.5 }, { pitch: '', dur: 1.5 },
    { pitch: 'C4', dur: 1 }, { pitch: 'C4', dur: 0.5 },
    { pitch: 'G4', dur: 1 }, { pitch: 'G4', dur: 0.5 },
    { pitch: 'G4', dur: 1 }, { pitch: 'G4', dur: 0.5 },
    { pitch: 'G4', dur: 1 }, { pitch: 'G4', dur: 0.5 },
    { pitch: 'F4', dur: 1 }, { pitch: 'G4', dur: 0.5 },
    { pitch: 'A4', dur: 1.5 },
    { pitch: '', dur: 1.5 }, { pitch: '', dur: 1.5 },
    { pitch: 'A4', dur: 1 }, { pitch: 'A4', dur: 0.5 },
    { pitch: 'A#4', dur: 1 }, { pitch: 'A#4', dur: 0.5 },
    { pitch: 'A#4', dur: 1 }, { pitch: 'A#4', dur: 0.5 },
    { pitch: 'D4', dur: 1 }, { pitch: 'D4', dur: 0.5 },
    { pitch: 'A#4', dur: 1 }, { pitch: 'A#4', dur: 0.5 },
    { pitch: 'A4', dur: 1 }, { pitch: 'A4', dur: 0.5 },
    { pitch: 'A4', dur: 1 }, { pitch: 'G4', dur: 0.5 },
    { pitch: 'F4', dur: 1 }, { pitch: 'F4', dur: 0.5 },
    { pitch: 'A4', dur: 1 }, { pitch: 'A4', dur: 0.5 },
    { pitch: 'G4', dur: 1 }, { pitch: 'G4', dur: 0.5 },
    { pitch: 'G4', dur: 1 }, { pitch: 'F4', dur: 0.5 },
    { pitch: 'E4', dur: 1 }, { pitch: 'E4', dur: 0.5 },
    { pitch: 'D4', dur: 1 }, { pitch: 'E4', dur: 0.5 },
    { pitch: 'F4', dur: 1.5 },
    { pitch: '', dur: 1.5 }, { pitch: '', dur: 1.5 },
  ], 3),
}, makeHappyDrums)
