import { repeat, withDrums } from './helpers'

export const song = withDrums({
  key: 'mary',
  emoji: '🐑',
  lyrics: [
    "Mary had a little lamb,",
    "Little lamb, little lamb,",
    "Mary had a little lamb,",
    "Its fleece was white as snow.",
    '',
    "And everywhere that Mary went,",
    "Mary went, Mary went,",
    "And everywhere that Mary went,",
    "The lamb was sure to go.",
    '',
    "It followed her to school one day,",
    "School one day, school one day,",
    "It followed her to school one day,",
    "Which was against the rules.",
    '',
    "It made the children laugh and play,",
    "Laugh and play, laugh and play,",
    "It made the children laugh and play,",
    "To see a lamb at school.",
    '',
    "Why does the lamb love Mary so?",
    "Love Mary so? Love Mary so?",
    "Why does the lamb love Mary so?",
    "The eager children cry.",
  ],
  notes: repeat([
    { pitch: 'E4', dur: 1.5 }, { pitch: 'D4', dur: 0.5 },
    { pitch: 'C4', dur: 1 }, { pitch: 'D4', dur: 1 },
    { pitch: 'E4', dur: 1 }, { pitch: 'E4', dur: 1 },
    { pitch: 'E4', dur: 2 },
    { pitch: 'D4', dur: 1 }, { pitch: 'D4', dur: 1 },
    { pitch: 'D4', dur: 2 },
    { pitch: 'E4', dur: 1 }, { pitch: 'G4', dur: 1 },
    { pitch: 'G4', dur: 2 },
    { pitch: 'E4', dur: 1.5 }, { pitch: 'D4', dur: 0.5 },
    { pitch: 'C4', dur: 1 }, { pitch: 'D4', dur: 1 },
    { pitch: 'E4', dur: 1 }, { pitch: 'E4', dur: 1 },
    { pitch: 'E4', dur: 1 }, { pitch: 'E4', dur: 1 },
    { pitch: 'D4', dur: 1 }, { pitch: 'D4', dur: 1 },
    { pitch: 'E4', dur: 1 }, { pitch: 'D4', dur: 1 },
    { pitch: 'C4', dur: 4 },
  ], 5),
})
