import { repeat, withDrums } from './helpers'

export const song = withDrums({
  key: 'oldMac',
  emoji: '🐷',
  lyrics: [
    'Old MacDonald had a farm,',
    'E-I-E-I-O,',
    'And on his farm he had a pig,',
    'E-I-E-I-O,',
    'With an oink oink here and an oink oink there,',
    'Here an oink, there an oink, everywhere an oink oink.',
    'Old MacDonald had a farm,',
    'E-I-E-I-O,',
    '',
    'Old MacDonald had a farm,',
    'E-I-E-I-O,',
    'And on his farm he had a cow,',
    'E-I-E-I-O,',
    'With a moo moo here and a moo moo there,',
    'Here a moo, there a moo, everywhere a moo moo.',
    'Old MacDonald had a farm,',
    'E-I-E-I-O,',
    '',
    'Old MacDonald had a farm,',
    'E-I-E-I-O,',
    'And on his farm he had a duck,',
    'E-I-E-I-O,',
    'With a quack quack here and a quack quack there,',
    'Here a quack, there a quack, everywhere a quack quack.',
    'Old MacDonald had a farm,',
    'E-I-E-I-O,',
    '',
    'Old MacDonald had a farm,',
    'E-I-E-I-O,',
    'And on his farm he had a horse,',
    'E-I-E-I-O,',
    'With a neigh neigh here and a neigh neigh there,',
    'Here a neigh, there a neigh, everywhere a neigh neigh.',
    'Old MacDonald had a farm,',
    'E-I-E-I-O,',
  ],
  notes: repeat([
    { pitch: 'G4', dur: 1 }, { pitch: 'G4', dur: 1 },
    { pitch: 'G4', dur: 1 }, { pitch: 'D4', dur: 1 },
    { pitch: 'E4', dur: 1 }, { pitch: 'E4', dur: 1 },
    { pitch: 'D4', dur: 2 },
    { pitch: 'B4', dur: 1 }, { pitch: 'B4', dur: 1 },
    { pitch: 'A4', dur: 1 }, { pitch: 'A4', dur: 1 },
    { pitch: 'G4', dur: 3 }, { pitch: 'D4', dur: 1 },
    { pitch: 'G4', dur: 1 }, { pitch: 'G4', dur: 1 },
    { pitch: 'G4', dur: 1 }, { pitch: 'D4', dur: 1 },
    { pitch: 'E4', dur: 1 }, { pitch: 'E4', dur: 1 },
    { pitch: 'D4', dur: 2 },
    { pitch: 'B4', dur: 1 }, { pitch: 'B4', dur: 1 },
    { pitch: 'A4', dur: 1 }, { pitch: 'A4', dur: 1 },
    { pitch: 'G4', dur: 3 }, { pitch: 'D4', dur: 0.5 }, { pitch: 'D4', dur: 0.5 },
    { pitch: 'G4', dur: 1 }, { pitch: 'G4', dur: 1 },
    { pitch: 'G4', dur: 1 }, { pitch: 'D4', dur: 0.5 }, { pitch: 'D4', dur: 0.5 },
    { pitch: 'G4', dur: 1 }, { pitch: 'G4', dur: 1 },
    { pitch: 'G4', dur: 1 }, { pitch: '', dur: 1 },
    { pitch: 'G4', dur: 0.5 }, { pitch: 'G4', dur: 0.5 },
    { pitch: 'G4', dur: 0.5 }, { pitch: '', dur: 0.5 },
    { pitch: 'G4', dur: 0.5 }, { pitch: 'G4', dur: 0.5 },
    { pitch: 'G4', dur: 0.5 }, { pitch: '', dur: 0.5 },
    { pitch: 'G4', dur: 0.5 }, { pitch: 'G4', dur: 0.5 },
    { pitch: 'G4', dur: 0.5 }, { pitch: 'G4', dur: 0.5 },
    { pitch: 'G4', dur: 1 }, { pitch: 'G4', dur: 1 },
    { pitch: 'G4', dur: 1 }, { pitch: 'G4', dur: 1 },
    { pitch: 'G4', dur: 1 }, { pitch: 'D4', dur: 1 },
    { pitch: 'E4', dur: 1 }, { pitch: 'E4', dur: 1 },
    { pitch: 'D4', dur: 2 },
    { pitch: 'B4', dur: 1 }, { pitch: 'B4', dur: 1 },
    { pitch: 'A4', dur: 1 }, { pitch: 'A4', dur: 1 },
    { pitch: 'G4', dur: 4 },
  ], 4),
})
