import { makeSixEightDrums, repeat, withDrums } from './helpers'

export const song = withDrums({
  key: 'row',
  emoji: '🚣',
  lyrics: [
    'Row, row, row your boat,',
    'Gently down the stream.',
    'Merrily, merrily, merrily, merrily,',
    'Life is but a dream.',
    '',
    'Row, row, row your boat,',
    'Gently down the stream.',
    'If you see a crocodile,',
    "Don't forget to scream!",
    '',
    'Row, row, row your boat,',
    'Gently down the river.',
    'If you see a polar bear,',
    "Don't forget to shiver!",
    '',
    'Row, row, row your boat,',
    'Gently to the shore.',
    'If you see a lion there,',
    "Don't forget to roar!",
    '',
    'Row, row, row your boat,',
    'Gently down the lake.',
    'If you see a little snake,',
    "Don't forget to shake!",
  ],
  notes: repeat([
    { pitch: 'C4', dur: 1.5 }, { pitch: 'C4', dur: 1.5 },
    { pitch: 'C4', dur: 1 }, { pitch: 'D4', dur: 0.5 },
    { pitch: 'E4', dur: 1.5 },
    { pitch: 'E4', dur: 1 }, { pitch: 'D4', dur: 0.5 },
    { pitch: 'E4', dur: 1 }, { pitch: 'F4', dur: 0.5 },
    { pitch: 'G4', dur: 3 },
    { pitch: 'C5', dur: 0.5 }, { pitch: 'C5', dur: 0.5 },
    { pitch: 'C5', dur: 0.5 },
    { pitch: 'G4', dur: 0.5 }, { pitch: 'G4', dur: 0.5 },
    { pitch: 'G4', dur: 0.5 },
    { pitch: 'E4', dur: 0.5 }, { pitch: 'E4', dur: 0.5 },
    { pitch: 'E4', dur: 0.5 },
    { pitch: 'C4', dur: 0.5 }, { pitch: 'C4', dur: 0.5 },
    { pitch: 'C4', dur: 0.5 },
    { pitch: 'G4', dur: 1 }, { pitch: 'F4', dur: 0.5 },
    { pitch: 'E4', dur: 1 }, { pitch: 'D4', dur: 0.5 },
    { pitch: 'C4', dur: 3 },
  ], 5),
}, makeSixEightDrums)
