import { repeat, withDrums } from './helpers'

export const song = withDrums({
  key: 'twinkle',
  emoji: '⭐',
  lyrics: [
    'Twinkle, twinkle, little star,',
    'How I wonder what you are!',
    'Up above the world so high,',
    'Like a diamond in the sky.',
    'Twinkle, twinkle, little star,',
    'How I wonder what you are!',
    '',
    'When the blazing sun is gone,',
    'When he nothing shines upon,',
    'Then you show your little light,',
    'Twinkle, twinkle, all the night.',
    'Twinkle, twinkle, little star,',
    'How I wonder what you are!',
  ],
  notes: repeat([
    { pitch: 'C4', dur: 1 }, { pitch: 'C4', dur: 1 },
    { pitch: 'G4', dur: 1 }, { pitch: 'G4', dur: 1 },
    { pitch: 'A4', dur: 1 }, { pitch: 'A4', dur: 1 },
    { pitch: 'G4', dur: 2 },
    { pitch: 'F4', dur: 1 }, { pitch: 'F4', dur: 1 },
    { pitch: 'E4', dur: 1 }, { pitch: 'E4', dur: 1 },
    { pitch: 'D4', dur: 1 }, { pitch: 'D4', dur: 1 },
    { pitch: 'C4', dur: 2 },
    { pitch: 'G4', dur: 1 }, { pitch: 'G4', dur: 1 },
    { pitch: 'F4', dur: 1 }, { pitch: 'F4', dur: 1 },
    { pitch: 'E4', dur: 1 }, { pitch: 'E4', dur: 1 },
    { pitch: 'D4', dur: 2 },
    { pitch: 'G4', dur: 1 }, { pitch: 'G4', dur: 1 },
    { pitch: 'F4', dur: 1 }, { pitch: 'F4', dur: 1 },
    { pitch: 'E4', dur: 1 }, { pitch: 'E4', dur: 1 },
    { pitch: 'D4', dur: 2 },
    { pitch: 'C4', dur: 1 }, { pitch: 'C4', dur: 1 },
    { pitch: 'G4', dur: 1 }, { pitch: 'G4', dur: 1 },
    { pitch: 'A4', dur: 1 }, { pitch: 'A4', dur: 1 },
    { pitch: 'G4', dur: 2 },
    { pitch: 'F4', dur: 1 }, { pitch: 'F4', dur: 1 },
    { pitch: 'E4', dur: 1 }, { pitch: 'E4', dur: 1 },
    { pitch: 'D4', dur: 1 }, { pitch: 'D4', dur: 1 },
    { pitch: 'C4', dur: 2 },
  ], 2),
})
