import { Schema as S } from 'effect'
import { m } from 'foldkit/message'
import { Language } from './i18n'

export const ClickedLanding = m('ClickedLanding')
export const ClickedCounter = m('ClickedCounter')
export const ClickedFindIt = m('ClickedFindIt')
export const ClickedBubbles = m('ClickedBubbles')
export const ClickedDraw = m('ClickedDraw')
export const ClickedMusicBox = m('ClickedMusicBox')
export const ClickedMemory = m('ClickedMemory')
export const ClickedAudioTest = m('ClickedAudioTest')
export const ClickedDarkMode = m('ClickedDarkMode')
export const ClickedSettings = m('ClickedSettings')
export const SetLanguage = m('SetLanguage', { value: Language })
export const SystemDarkModeChanged = m('SystemDarkModeChanged')
export const ToggleMute = m('ToggleMute')
export const SetSpeechRate = m('SetSpeechRate', { value: S.Number })
export const SetSpeechPitch = m('SetSpeechPitch', { value: S.Number })
export const SettingsPersisted = m('SettingsPersisted')
export const SettingsDragStarted = m('SettingsDragStarted', { screenX: S.Number })
export const SettingsDragMoved = m('SettingsDragMoved', { screenX: S.Number })
export const SettingsDragEnded = m('SettingsDragEnded')
export const ResetSettings = m('ResetSettings')
export const ConfirmResetSettings = m('ConfirmResetSettings')
export const CancelResetSettings = m('CancelResetSettings')
export const ExportSettings = m('ExportSettings')
export const ImportSettings = m('ImportSettings')
export const ImportedSettings = m('ImportedSettings', { data: S.String })
export const SettingsImportFailed = m('SettingsImportFailed')
export const DismissMessage = m('DismissMessage')
export const CopyExportData = m('CopyExportData')
export const SetExportData = m('SetExportData', { value: S.String })
export const ApplyImport = m('ApplyImport')
export const LandingDragStarted = m('LandingDragStarted', { index: S.Number })
export const LandingDroppedOn = m('LandingDroppedOn', { index: S.Number })
export const LandingDragEnded = m('LandingDragEnded')
export const LandingSettingsDragStarted = m('LandingSettingsDragStarted', { index: S.Number })
export const LandingSettingsDroppedOn = m('LandingSettingsDroppedOn', { index: S.Number })
export const LandingSettingsDragEnded = m('LandingSettingsDragEnded')
export const LandingToggleGameVisibility = m('LandingToggleGameVisibility', { index: S.Number })
